#!/usr/bin/env python3
import py_compile
import os

top_lvl_dir = os.path.dirname(os.path.realpath(__file__))
os.makedirs(f'{top_lvl_dir}/build/src', exist_ok=True)
py_compile.compile(f'{top_lvl_dir}/src/gaccli.py', cfile=f'{top_lvl_dir}/build/src/gaccli.pyc')
py_compile.compile(f'{top_lvl_dir}/src/gaccmd.py', cfile=f'{top_lvl_dir}/build/src/gaccmd.pyc')
py_compile.compile(f'{top_lvl_dir}/src/gacmain.py', cfile=f'{top_lvl_dir}/build/src/gacmain.pyc')
py_compile.compile(f'{top_lvl_dir}/src/gacworker.py', cfile=f'{top_lvl_dir}/build/src/gacworker.pyc')
